apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
spec:
  type: ClusterIP
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
    protocol: TCP
  - name: zookeeper
    port: 2181
    targetPort: 2181
    protocol: TCP
  selector:
    app.kubernetes.io/name: kafka

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka
    spec:
      automountServiceAccountToken: false
      containers:
      - name: kafka
        image: nuvo/docker-kafka:latest
        imagePullPolicy: Never
        env:
        - name: AUTO_CREATE_TOPICS
          value: "true"
        - name: ADVERTISED_PORT
          value: "9092"
        - name: ADVERTISED_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - name: kafka
          containerPort: 9092
        - name: zookeeper
          containerPort: 2181
